* haskell-invoice

** Usage

This project uses [[https://nixos.org/][nix]]. It also depends on [[https://wkhtmltopdf.org/][wkhtmltopdf]], which will be installed with the ~haskell-invoice~ bash script.

Build:
#+begin_src sh
$ nix-build
#+end_src

Add or edit the parameter files (see following sections)
- ~defaults.yaml~
- ~0047.yaml~ (a file with the invoice number as its name)
- ~email.yaml~

Create an invoice:
#+begin_src sh
$ ./haskell-invoice 0047.yaml
#+end_src

This will create the invoice file ~0047.pdf~.

** Parameters

The invoice body information must be in YAML format (e.g., see ~0047.yaml~). The file should be provided as an argument to ~haskell-invoice~. A second file, ~defaults.yaml~ should be located in the same directory as the invoice body file. See ~defaults.yaml~ and ~0047.yaml~ for basic example.

~defaults.yaml~ is for setting the default ~from~ and ~notes (string, optional)~ information to use in every invoice. These can be overridden by providing values in the invoice body.

The invoice body contains:
- date (string, optional)
- from (optional)
  - name (string)
  - website (string, optional)
  - email (string)
- to
  - name (string)
  - email (string)
- items (list)
  - name (string)
  - description (string, optional)
  - qtyHrs (number)
  - unitPrice (number)

** Email

Put email and SMTP information in ~email.yaml~, in the same directory as the invoice body. For Gmail, create an [[https://myaccount.google.com/u/1/apppasswords][app password]] ([[https://support.google.com/accounts/answer/185833?hl=en][help center]]).

** Adding dependencies

- Update haskell-invoice.cabal
- Update haskell-invoice.nix

If the package is not found, get it from GitHub:

#+begin_src sh
$ cabal2nix --no-check https://github.com/JustusAdam/mustache.git --revision 530c0f10188fdaead9688d56f728b87fabcb228b > nix/mustache.nix
#+end_src

- Update default.nix

For more information, read: https://github.com/Gabriella439/haskell-nix/tree/main/project1
