* haskell-invoice

** Description

Easily generate PDF invoices which are emailed automatically to the client. From a simple YAML file, a PDF invoice is generated and sent to the client.

Example:
#+begin_src yaml
to:
  name: Alice Smith
  email: alice.smith@gmail.com
items:
  - name: Development
    description: Website design and development.
    qtyHrs: 65
    unitPrice: 100
  - name: Domain hosting
    description: 1 year
    qtyHrs: 1
    unitPrice: 180
#+end_src

See [[examples][examples]] for complete exampes.

** Features

- User-friendly templating
  - The invoice and email templates use [[https://mustache.github.io/][Mustache]] for easy customization
- Automatic emailing
  - The invoice is automatically sent to the client from your account.
- Type-safe YAML parsing
  - For example, ~qtyHrs~ (quantity/hours) is supposed to be a number, so if any other type of value is given (e.g., ~abc~), the parsing will fail and show a helpful error message. Likewise, any missing parameters will be caught.
- Type-safe money operations
  - The [[https://hackage.haskell.org/package/safe-money][safe-money]] Haskell library offers type-safe and lossless encoding and operations for monetary values in all world currencies. This means that rounding errors won't occur when calculating the invoice prices.

** Usage

This project uses [[https://nixos.org/][nix]]. It also depends on [[https://wkhtmltopdf.org/][wkhtmltopdf]], which will be installed with the resulting application.

Build:
#+begin_src sh
$ nix-build
#+end_src

Add or edit the parameter files (see following sections)
- ~defaults.yaml~
- ~0047.yaml~ (a file with the invoice number as its name)
- ~email.yaml~

Create an invoice:
#+begin_src sh
$ ./result/bin/haskell-invoice 0047.yaml
#+end_src

This will create the invoice file ~0047.pdf~.

** Parameters

The invoice body information must be in YAML format (e.g., see ~0047.yaml~). The file should be provided as an argument to ~haskell-invoice~. A second file, ~defaults.yaml~ should be located in the same directory as the invoice body file. See ~defaults.yaml~ and ~0047.yaml~ for basic example.

~defaults.yaml~ is for setting the default ~from~ and ~notes (string, optional)~ information to use in every invoice. These can be overridden by providing values in the invoice body.

The invoice body contains:
- date (string, optional)
- from (optional)
  - name (string)
  - website (string, optional)
  - email (string)
- to
  - name (string)
  - email (string)
- items (list)
  - name (string)
  - description (string, optional)
  - qtyHrs (number)
  - unitPrice (number)

** Email

Put email and SMTP information in ~email.yaml~, in the same directory as the invoice body. For Gmail, create an [[https://myaccount.google.com/u/1/apppasswords][app password]] ([[https://support.google.com/accounts/answer/185833?hl=en][help center]]).

** Adding dependencies

- Update haskell-invoice.cabal
- Update haskell-invoice.nix

If the package is not found, get it from GitHub:

#+begin_src sh
$ cabal2nix --no-check https://github.com/JustusAdam/mustache.git --revision 530c0f10188fdaead9688d56f728b87fabcb228b > nix/mustache.nix
#+end_src

- Update default.nix

For more information, read: https://github.com/Gabriella439/haskell-nix/tree/main/project1

** TO-DO

- Allow confirmation before emailing PDF
